<?php /* Template Name: Terms & Conditions */ ?>
<?php get_header(); ?>

<section class="page-content-header terms-conditions-header">
    <div class="container">
        <div class="header-content-box">
            <?php 
                $terms_condition_header_content = get_field('terms_&_condition_content');
                $heading = $terms_condition_header_content['heading'] ?? '';  
                $description = $terms_condition_header_content['description'] ?? '';
            ?>

            <?php if ($heading): ?>
                <h2><?php echo $heading; ?></h2>
            <?php endif; ?>

            <?php if ($description): ?>
                <p><?php echo $description; ?></p>
            <?php endif; ?>
        </div>
    </div>
</section>

<section class="page-content-wrap terms-conditions-content">
    <div class="container">
        <div class="page-content-inner">
            <h4>March 8, 2024</h4>
            <p>This website (hereafter referred to as “Website”) is owned and operated by BlueRidge Meds (hereinafter referred to as "BlueRidge Meds", “Company”, "we", "our", or "us"). The terms "you" or “your(s)” denote the user of this Website. The present Terms & Conditions ("Terms") articulate the permissible use of our Website and its content. By accessing and using our Website, you hereby agree to be bound by these Terms, acknowledging that you have read, comprehended, and fully consent to the Terms set forth below. Should you have any inquiries or concerns regarding any of these Terms, you may contact us by email at ask@blueridgemeds.com before utilizing our Website.</p>
            <p>YOU MUST BE EIGHTEEN (18) YEARS OF AGE OR OLDER AND POSSESS THE LEGAL CAPACITY TO CONSENT TO THESE TERMS. ACCORDINGLY, IF YOU ARE UNDER THE AGE OF 18 OR IF YOU DO NOT AGREE WITH ALL OF THESE TERMS, YOU ARE EXPRESSLY PROHIBITED FROM USING THE WEBSITE, ITS ASSOCIATED SERVICES, AND YOU MUST DISCONTINUE USE IMMEDIATELY.</p>
            <p>BlueRidge Meds retains the exclusive right to modify or amend these Terms at any given time without prior notice. By utilizing our Website, you are signifying your agreement to the Terms in their most current form, regardless of whether you have thoroughly read them or not. If you do not agree with these Terms, please refrain from further use of this Website, as well as its programs, products, and services.
            </p>
            <h4>Use of Information Received through the Website</h4>
            <p>In using this Website, you agree that you have reviewed our Privacy Policy, which includes critical information regarding the collection, usage, potential disclosure, and protection of the data you have provided. By accepting the Terms, you are also signifying your agreement with our Privacy Policy, which is hereby incorporated by reference.</p>
            <h4>Third Parties</h4>
            <p>By using our Website you acknowledge that we lack control over third-party networks accessed while utilizing the Website; accordingly, any delays or disruptions to external network transmissions fall entirely outside of our control.</p>
            <h4>Medical Notice</h4>
            <p>This Website has been created to provide information about healthcare programs, products, and services and should never be construed as medical advice for any person, including patients of the Company.  Nothing on this Website is intended to substitute for professional medical advice, diagnosis, or treatment.</p>
            <p>THIS WEBSITE IS NOT AN EMERGENCY RESPONSE SERVICE AND ANY PERSON WHO IS AWARE OF AN EMERGENCY SITUATION OR BELIEVES THAT A PERSON MAY BE AT RISK OF INJURY OR DEATH OR WHO MAY HARM THEMSELVES OR ANOTHER PERSON SHOULD DIAL "911" OR AN APPROPRIATE EMERGENCY RESPONDER. OUR COMPANY IS UNDER NO OBLIGATION TO MONITOR OR RESPOND TO COMMUNICATIONS MADE TO THIS WEBSITE.</p>
            <p>The Website, including its programs, products, services, and all associated materials, whether accessible on or through the Website, constitute the exclusive property of the Company and are safeguarded by copyright, trademark, and other pertinent intellectual property laws. This encompasses but is not confined to, the design, visual aspects, and integrated graphics.</p>
            <p>Your usage of the contents of this Website is solely authorized to the extent expressly permitted by us. Without obtaining prior express written authorization from us, you are prohibited from engaging in the copying, reproducing, modifying, republishing, uploading, posting, transmitting, or distributing of any documents or information from this Website, regardless of the format or means employed. Furthermore, you bear the sole responsibility for acquiring permission before utilizing any copyrighted material available on this Website.</p>
            <p>Any unauthorized utilization of the materials presented on this Website may violate copyright, trademark, and other applicable laws, potentially resulting in criminal or civil liabilities.</p>
            <p>Any trademarks, taglines, and logos displayed on the Website are trademarks belonging to us. Any trademarks reproduced on this Website, which are not the property of, or licensed to us, are the property of their respective owners. Any use, including framing, meta tags, or other text utilizing these trademarks, or other trademarks displayed, is strictly prohibited without our express written consent.</p>
            <h4>External Affiliates</h4>
            <p>Our Website offers registered users access to various programs, products, and services, which may be provided directly by us or by external medical providers, pharmacies, or vendors affiliated with the Company. Additionally, the Company may grant you access to third-party telemedicine services. These services utilize contracted physicians and other healthcare professionals who provide certain healthcare services through associated platforms (collectively referred to as “Providers”)</p>
            <p>By accepting the Terms, you acknowledge and agree that any services rendered to you by the pharmacies, services, and/or Providers are subject to the Terms, and that the pharmacies, medical groups, and Providers are designated as third-party beneficiaries of these Terms.</p>
            <p>The Company does not exercise control over or interfere with the methodology or manner of facilitation and/or practice of medicine rendered by the contracted Providers. Each medical group or Provider holds sole responsibility for directing the medical care, healthcare, and/or treatment they provide to you. By accepting the Terms, you acknowledge and agree that BlueRidge Meds is not a healthcare provider. Furthermore, by utilizing this Website, you do not enter into a doctor-patient or other healthcare provider-patient relationship with us. However, by using this Website, you may establish a doctor-patient or other healthcare provider-patient relationship with a medical group and/or one or more Providers. Additionally, the Company does not control or interfere with any professional service provided by the pharmacies, each of which is solely responsible for rendering professional services via the Website and associated platforms.</p>
            <p>By accepting the Terms, you formally acknowledge and agree that the medical groups and/or Providers may utilize associated platforms to transmit messages, reports, and emails to you pertaining to your diagnosis and/or treatment. You fully comprehend and concur that we bear no liability or responsibility for the security or privacy of any communications services you employ to receive the aforementioned messages, reports, and emails sent through associated platforms. Furthermore, you acknowledge and agree that it is solely your responsibility to diligently monitor and respond to these messages, reports, and emails. Neither we, the medical group, nor any Provider shall be held liable or accountable in any manner, and you shall refrain from holding us, the medical group, or any Provider responsible for any loss, injury, or claims of any nature resulting from your failure to read or respond to these messages or your failure to adhere to any treatment recommendations or instructions provided by the medical group(s) or Provider(s).</p>
            <p>Moreover, the utilization of our Website does not establish a healthcare provider-patient relationship, but rather a direct customer relationship for the purpose of purchasing prescriptions, eCommerce products, other programs, or services directly from our Company through the Website. In connection with this relationship, you may furnish personal information, including health information, to the Company, or authorize others to provide it on your behalf. Any information shared is subject to the Company's Privacy Policy.</p>
            <h4>Arbitration</h4>
            <p>To the fullest extent permitted by applicable law, by using this Website and entering into this agreement of Terms, you hereby acknowledge and agree that any and all disputes, controversies, or claims arising out of or in connection with these Terms or the programs, products or service, including, without limitation, any disputes between you and us, our partnering pharmacies, medical groups, and/or Providers, shall be resolved exclusively through binding, individual arbitration on an individual basis. By agreeing to these Terms, you knowingly, voluntarily, and irrevocably waive your rights to a jury trial and to participate in a class action lawsuit or class-wide arbitration. You further acknowledge and agree that you may only bring claims against us in your individual capacity, and not as a plaintiff or class member in any purported class or representative action.</p>
            <h4>User Materials</h4>
            <p>In adherence to our Privacy Policy, all communications and materials transmitted to or via this Website, irrespective of the method of transmission (electronic mail or otherwise), and regardless of the purpose, shall be considered non-confidential and non-proprietary. While you maintain ownership rights over these communications or materials, you hereby confer upon us a non-exclusive, perpetual, fully paid, royalty-free, and global right to reproduce, distribute, display, perform, publish, translate, adapt, modify, and otherwise utilize such materials.</p>
            <p>Please refrain from submitting confidential or proprietary information to us unless we have a mutual written agreement in place. We acknowledge and respect the intellectual property rights of others and request that you do the same. If you or any user of this Website believes that their copyright, trademark, or other property rights have been infringed upon by a posting on this Website, you or the user should promptly notify us.</p>
            <p>In accordance with the provisions set forth in the Digital Millennium Copyright Act, Title 17, United States Code, Section 512(c), the designated agent responsible for receiving and responding to notifications of alleged copyright infringements can be contacted via the following email address: ask@blueridgemeds.com</p>
            <h4>Product Displays</h4>
            <p>We make every effort to display as accurately as possible the colors, features, specifications, and details of the products available through our Website. However, we do not guarantee that the colors, features, specifications, and details of the products will be accurate, complete, reliable, current, or free of other errors, and your electronic display may not accurately reflect the actual colors and details of the products. All products are subject to availability, and we cannot guarantee that items will be in stock. We reserve the right to discontinue any products at any time for any reason. Prices for all products are subject to change.</p>
            <h4>Return Policy</h4>
            <p>Please review our Return Policy prior to making any purchases.</p>
            <h4>Shipping Policy</h4>
            <p>Please review our Shipping Policy prior to making any purchases.</p>
            <h4>External Website Links and Social Media Utilization</h4>
            <p>Occasionally, this Website may also incorporate hyperlinks to other websites or social media platforms. These links are furnished for your convenience to furnish supplementary information and to facilitate your easy access to other websites of interest. However, it is essential to acknowledge that once you utilize these links to exit our Website, we relinquish control over those external websites or social media platforms. Accordingly, we bear no responsibility for the safeguarding and privacy of any information you furnish while visiting such sites or social media platforms. Furthermore, please note that even if operated by us, these external sites and social media platforms are not governed by the Terms set forth herein.</p>
            <h4>Prohibited Activities</h4>
            <p>You may not access or use our Website for any purpose other than that for which we make it available. As a user of our Website, you agree not to:</p>
            <ul>
                <li>Systematically retrieve data or other content from the Website to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.</li>
                <li>Trick, defraud, or mislead us or our users, especially in any attempt to learn sensitive account information such as user passwords.</li>
                <li>Circumvent, disable, or otherwise interfere with security-related features of the Website.</li>
                <li>Disparage, tarnish, or otherwise harm, in our opinion, users, us, or our Website.</li>
                <li>Use any information obtained from the Website in order to harass, abuse, or harm users.</li>
                <li>Make improper use of our support services or submit false reports of abuse or misconduct.</li>
                <li>Use the Website in a manner inconsistent with any applicable laws or regulations.</li>
                <li>Engage in unauthorized framing of or linking to the Website.</li>
                <li>Upload or transmit (or attempt to upload or to transmit) viruses, Trojan horses, or other material, including excessive use of capital letters and spamming (continuous posting of repetitive text), that interferes with the use, features, functions, operation, or maintenance of the Website.</li>
                <li>Engage in any automated use of the system, such as using scripts to send comments or messages, or using any data mining, robots, or similar data gathering and extraction tools.</li>
                <li>Attempt to impersonate another user or person or use the username of another user.</li>
                <li>Upload or transmit (or attempt to upload or to transmit) any material that acts as a passive or active information collection or transmission mechanism, including without limitation, clear graphics interchange formats ("gifs"), 1x1 pixels, web bugs, cookies, or other similar devices (sometimes referred to as “spyware” or “passive collection mechanisms” or “pems”).</li>
                <li>Interfere with, disrupt, or create an undue burden on the Website or the networks or services connected to the Website.</li>
                <li>Harass, annoy, intimidate, or threaten any of our employees or agents engaged in providing any portion of the Website’s services to you.</li>
                <li>Attempt to bypass any measures of the Website designed to prevent or restrict access to the Website, or any of its connected networks or services.</li>
                <li>Copy or adapt the Website’s software, including but not limited to Flash, PHP, HTML, JavaScript, or other code.</li>
            </ul>
            <h4>Disclaimer</h4>
            <p>Please be advised that prior to accessing our Website or making the purchase of any program, product, or service from or through us, you retain the right to seek legal counsel. We assume no liability for your personal actions or choices made before, during, or after the use of our Website.</p>
            <p>Despite any legal limitations, any misuse or non-use of this information is at your own risk and you release us from any liability or loss incurred by you, your business, family, or any other individuals. Furthermore, regardless of legal limitations, you recognize that you are exercising your own due diligence and risk assessment in your decision-making and are voluntarily making these decisions acknowledging the potential risks involved.</p>
            <p>Every effort has been expended to furnish you with the most precise and up-to-date information available. Nevertheless, due to the dynamic and evolving nature of information, we cannot provide a guarantee regarding the accuracy of the content presented on our Website or assert that all related information is entirely current or directly applicable to your specific circumstances. You acknowledge the possibility that the information and materials contained within our Website or associated with our programs, products, or services might encompass inaccuracies or errors. To the maximum extent permitted by law, we expressly disclaim any liability for such inaccuracies or errors and are under no obligation to notify you of any updates or modifications as they occur.</p>
            <p>We try to ensure that the availability of our Website is continuous and free from errors. However, we are unable to guarantee that your access will not be suspended or restricted at times, including for the purpose of enabling repairs, maintenance, or the incorporation of new services. All reasonable efforts will be made to minimize the frequency and duration of any suspension or restriction. Additionally, neither we nor any third parties shall provide any warranty or assurance regarding the accuracy, timeliness, performance, completeness, or suitability of the information and materials obtained or provided through our Website for any specific purpose.</p>
            <p>In addition, although this Website may be accessible worldwide, we make no representation that materials on this Website are appropriate or available for use in locations outside the United States, and accessing them from territories where their contents are illegal is prohibited. Those who choose to access this Website from other locations do so on their own initiative and are responsible for compliance with local laws. Any offer for any product, service, and/or information made in connection with this Website is void where prohibited.</p>
            <h4>Exclusive Remedy</h4>
            <p>If you experience dissatisfaction with your utilization of this Website or with the Terms set forth herein, your sole and exclusive recourse shall be the cessation of your use of this Website.</p>
            <h4>No Warranty</h4>
            <p>To the fullest extent permitted by applicable law, the website and content (including user submissions) are furnished "AS IS" and without warranties of any sort, either express or implied, encompassing but not restricted to implied warranties of merchantability, fitness for a specific purpose, title, and non-infringement. We grant no warranty, implicit or explicit, concerning the accuracy, completeness, or appropriateness of our website, including the products or services accessible for purchase therein, for any purpose.</p>
            <h4>LIMITATION OF LIABILITY</h4>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL WE BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM YOUR USE OF, OR INABILITY TO USE, THIS WEBSITE OR CONTENT OR ANY WEBSITE OR CONTENT LINKED FROM THIS WEBSITE, INCLUDING, BUT NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES, INCLUDING, BUT NOT LIMITED TO, ANY LOST PROFITS, BUSINESS INTERRUPTION, LOST SAVINGS OR LOSS OF PROGRAMS OR OTHER DATA, EVEN IF WE ARE EXPRESSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THIS LIMITATION OF LIABILITY APPLIES TO ALL CAUSES OF ACTION, WHETHER BASED IN CONTRACT, WARRANTY, TORT, OR ANY OTHER LEGAL THEORIES. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU.</p>
            <h4>Confidentiality and Security</h4>
            <p>To use our Website, we may seek personal data or information, including your name, e-mail address, phone number, street address, billing information, interests, or other personally identifying information (“Personal Information”), or you may offer or provide a comment, photo, image, video, or any other submission to us when using or participating in our Website (“Other Information”).</p>
            <p>By providing such Personal Information or Other Information to us, you grant us permission to use and store such information. We, in turn, will use our best efforts to keep your Personal Information safe, secure, and confidential in accordance with these Terms and our full Privacy Policy. We have reasonable security measures in place to prevent the loss, misuse, and alteration of the information that is obtained from you, but we make no assurances about our ability to prevent any such loss, or misuse, to you or to any third party arising out of any such loss, misuse, or alteration. However, due to the nature of the internet, we cannot completely ensure or warrant the security of any information transmitted to us or through our Website, platform, or associated platforms and, therefore, it is done at your own risk. If you believe that any of your Personal Information is incorrect or incomplete, please contact us as soon as possible. We will promptly correct any Personal Information found to be incorrect.</p>
            <h4>Electronic Communications, Transactions, and Signatures</h4>
            <p>Visiting the Website, sending us emails, and completing online forms constitute electronic communications. You consent to receive electronic communications, and you agree that all agreements, notices, disclosures, and other communications we provide to you electronically, via email, and on the Website, satisfy any legal requirement that such communication be in writing.</p>
            <p>YOU HEREBY AGREE TO THE USE OF ELECTRONIC SIGNATURES, CONTRACTS, ORDERS, AND OTHER RECORDS, AND TO ELECTRONIC DELIVERY OF NOTICES, POLICIES, AND RECORDS OF TRANSACTIONS INITIATED OR COMPLETED BY US OR VIA THE SERVICES.</p>
            <p>You hereby waive any rights or requirements under any statutes, regulations, rules, ordinances, or other laws in any jurisdiction that require an original signature or delivery or retention of non-electronic records, or to payments or the granting of credits by any means other than electronic means.</p>
            <h4>Indemnification</h4>
            <p>You agree to defend, indemnify, and hold us harmless, including our subsidiaries, affiliates, vendors, medical group, contracted Providers and all of our respective officers, agents, partners, and employees, from and against any loss, damage, liability, claim, or demand, including reasonable attorneys' fees and expenses, made by any third party due to or arising out of (1) use of the Website, our associated platform(s) and services; (2) breach of these Terms; (3) any breach of your representations and warranties set forth in these Terms: (4) your violation of the rights of a third party, including but not limited to intellectual property rights; or (5) any overt harmful act toward any other user of the Website with whom you connected. Notwithstanding the foregoing, we reserve the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate, at your expense, with our defense of such claims We will use reasonable efforts to notify you of any such claim, action, or proceeding which is subject to this indemnification upon becoming aware of it.</p>
            <h4>Governing Law</h4>
            <p>This Website is accessible by individuals residing in all 50 states within the United States of America, and Internationally. This Agreement will be governed, however, by and construed in accordance with the substantive laws of the State of Delaware in the United States of America, without regard to conflict of laws, and all disputes arising under or relating to this Agreement shall be brought and resolved solely and exclusively in the State Court located in Delaware. Should any legal action be commenced in connection with this Agreement, the prevailing party in such action shall be entitled to recover, in addition to court costs, such amount as the court may adjudge as reasonable attorneys’ fees.</p>
            <h4>Severability</h4>
            <p>In the event that any clause or provision contained within these Terms shall be deemed to be invalid or otherwise unenforceable, such portion shall be interpreted in a manner that is consistent with applicable law and which most closely reflects the original intentions of the parties. The remaining provisions contained herein shall remain in full force and effect.</p>
            <h4>No Waiver</h4>
            <p>Any failure by the Company to enforce or exercise any provision of these Terms or related rights shall not constitute a waiver of that right or provision.</p>
            <h4>California Users and Residents</h4>
            <p>While we take all complaints seriously and strive to resolve them satisfactorily, if any complaint with us is not satisfactorily resolved, you can contact the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs in writing at 1625 North Market Blvd., Suite N 112, Sacramento, California 95834 or by telephone at 1 (800) 952-5210.</p>
            <h4>Miscellaneous</h4>
            <p>You may not assign your rights or obligations under these Terms to any third party and any purported attempt to do so shall be null and void. The Company may freely assign its rights and obligations under these Terms.</p>
            <p>You agree not to sell, resell, reproduce, duplicate, copy, or use for any commercial purposes any portion of this Website without written permission from BlueRidge Meds.</p>
            <p>The captions of these Terms are for convenience and ease of reference only and in no way define, describe, extend, or limit the scope or intent of these Terms.</p>
            <p>By viewing this Website, you agree to not engage in any conduct or communications in a public setting, including social media, designed to, or that in fact, disparage us, our Website, programs, products, or services. Should you have concerns or questions about this Website or our programs, products, or services, you are to contact us directly at ask@blueridgemeds.com</p>
            <p>If you have any questions about any of these Terms, please contact us at <a href="mailto:ask@blueridgemeds.com">ask@blueridgemeds.com</a></p>
        </div>
    </div>
</section>

<section class="live-support-section">
    <div class="container">
        <div class="support-content-wrap">
            <div class="support-info">
                <h3>Do you still have questions?</h3>
                <p>Call us for LIVE support now!</p>
                <a href="tel:1-855-295-2583">1-855-295-BLUE (2583)</a>
            </div>
            <div class="support-action">
                <a class="chat-with-us" href="/contact-us" title="Chat with us">Chat with us</a>
            </div>
        </div>
    </div>
</section>

<?php get_footer() ?>